# abc2ly
# Autogenerated from man page /usr/share/man/man1/abc2ly.1.gz
complete -c abc2ly -l version -d 'show version number and exit'
complete -c abc2ly -s h -l help -d 'show this help and exit'
complete -c abc2ly -s o -l output -d 'write output to FILE'
complete -c abc2ly -s s -l strict -d 'be strict about success'
complete -c abc2ly -s b -l beams -d 'preserve ABC\'s notion of beams'
complete -c abc2ly -s q -l quiet -d 'suppress progress messages REPORTING BUGS Report bugs via bug-lilypond@gnu'

