# bibtex.original
# Autogenerated from man page /usr/share/man/man1/bibtex.original.1.gz
complete -c 'bibtex.original' -o min-crossrefs -d 'option defines the minimum number of crossref required for automatic inclusio…'
complete -c 'bibtex.original' -o terse -d 'option,  operates silently'

