# convert-ly
# Autogenerated from man page /usr/share/man/man1/convert-ly.1.gz
complete -c convert-ly -l version -d 'show version number and exit'
complete -c convert-ly -s h -l help -d 'show this help and exit'
complete -c convert-ly -s f -l from -d 'start from VERSION [default: version found in file]'
complete -c convert-ly -s e -l edit -d 'edit in place'
complete -c convert-ly -s l -l loglevel -d 'Print log messages according to LOGLEVEL (NONE, ERROR, WARNING, PROGRESS (def…'
complete -c convert-ly -s n -l no-version -d 'do not add version command if missing'
complete -c convert-ly -s c -l current-version -d 'force updating version number to 2. 24. 1'
complete -c convert-ly -s d -l diff-version-update -d 'only update version number if file is modified'
complete -c convert-ly -s s -l show-rules -d 'show rules [default: -f 0, -t 2. 24. 1]'
complete -c convert-ly -s t -l to -d 'convert to VERSION [default: 2. 24. 1]'
complete -c convert-ly -s b -l backup-numbered -d 'make a numbered backup [default: filename. ext~]'
complete -c convert-ly -s w -l warranty -d 'show warranty and copyright EXAMPLES $ convert-ly -e old. ly'

