# dtplite
# Autogenerated from man page /usr/share/man/man1/dtplite.1.gz
complete -c dtplite -s o -d 'This is the form for use case [1]'
complete -c dtplite -o merge -d 'This is the form for use case [3]'
complete -c dtplite -o exclude -d 'This option specifies an exclude (glob) pattern'
complete -c dtplite -o ext -d 'If the name of an output file has to be derived from the name of an input fil…'
complete -c dtplite -o header -d 'This option can be used if and only if the selected format provides an engine…'
complete -c dtplite -o footer -d 'Like -header, except that: Any navigation buttons are ignored, the correspond…'
complete -c dtplite -o style -d 'This option can be used if and only if the selected format provides an engine…'
complete -c dtplite -o toc -d 'This option specifies a doctoc file to use for the table of contents instead …'
complete -c dtplite -o pre+toc
complete -c dtplite -o post+toc -d 'This option specifies additional doctoc files (or texts) to use in the naviga…'
complete -c dtplite -o prenav -o postnav
complete -c dtplite -o nav

