# etf2ly
# Autogenerated from man page /usr/share/man/man1/etf2ly.1.gz
complete -c etf2ly -s h -l help -d 'show this help and exit'
complete -c etf2ly -l version -d 'show version number and exit'
complete -c etf2ly -s o -l output -d 'write output to FILE'
complete -c etf2ly -s w -l warranty -d 'show warranty and copyright REPORTING BUGS Report bugs via bug-lilypond@gnu'

