# frescobaldi
# Autogenerated from man page /usr/share/man/man1/frescobaldi.1.gz
complete -c frescobaldi -s v -l version -d 'Show version information'
complete -c frescobaldi -s h -l help -d 'Show help about options and exit'
complete -c frescobaldi -s e -l encoding -d 'Encoding to use'
complete -c frescobaldi -s l -l line -d 'Line number to go to, starting at 1'
complete -c frescobaldi -s c -l column -d 'Column to go to, starting at 0'
complete -c frescobaldi -l start -d 'Session to start (`none\' for empty session)'
complete -c frescobaldi -s n -l new -d 'Always start a new instance'

