# lilypond-invoke-editor
# Autogenerated from man page /usr/share/man/man1/lilypond-invoke-editor.1.gz
complete -c lilypond-invoke-editor -s h -l help -d 'show this help'
complete -c lilypond-invoke-editor -s v -l version -d 'show version SEE ALSO The full documentation for lilypond-invoke-editor is ma…'

