# lilymidi
# Autogenerated from man page /usr/share/man/man1/lilymidi.1.gz
complete -c lilymidi -l version -d 'show program\'s version number and exit'
complete -c lilymidi -s h -l help -d 'show this help message and exit'
complete -c lilymidi -l filter-tracks -d 'display only tracks numbers, of those track names matching REGEXP'
complete -c lilymidi -l prefix-tracks -d 'prefix filtered track numbers with PREFIX'
complete -c lilymidi -l dump -d 'just dump parsed contents of the MIDI file'
complete -c lilymidi -l pretty -d 'dump parsed contents of the MIDI file in humanreadable form (implies --dump) …'

