# lilysong
# Autogenerated from man page /usr/share/man/man1/lilysong.1.gz
complete -c lilysong -l version -d 'show program\'s version number and exit'
complete -c lilysong -s h -l help -d 'show this help message and exit'
complete -c lilysong -l list-voices -d 'list available Festival voices'
complete -c lilysong -l list-languages -d 'list available Festival languages'
complete -c lilysong -s p -l play-program -d 'use PROGRAM to play song immediately SEE ALSO The full documentation for lily…'

