# ly
# Autogenerated from man page /usr/share/man/man1/ly.1.gz
complete -c ly -s v -l version -d 'show version number and exit'
complete -c ly -s h -l help -d 'show this help text and exit'
complete -c ly -s i -l in-place -d 'overwrite input files'
complete -c ly -s o -l output -d 'output file name'
complete -c ly -s e -l encoding -d '(input) encoding (default UTF-8)'
complete -c ly -l output-encoding -d 'output encoding (default to input encoding)'
complete -c ly -s l -l language -d 'default pitch name language (default to ânederlandsâ)'
complete -c ly -s d -d 'set a variable'

