# nnslog
# Autogenerated from man page /usr/share/man/man1/nnslog.1.gz
complete -c nnslog -o host -d 'If this option is not specified it defaults to localhost'
complete -c nnslog -o port -d 'If this option is not specified it defaults to 38573'

