# page
# Autogenerated from man page /usr/share/man/man1/page.1.gz
complete -c page -l help -l version -d 'encountered first has precedence'
complete -c page -o wr -o tr -d error
complete -c page -s c -d 'And now the recognized options and their arguments, if they have any:'
complete -c page -s h
complete -c page -s '?' -d 'When one of these options is found on the command line all arguments coming b…'
complete -c page -s V -d 'When one of these options is found on the command line all arguments coming b…'
complete -c page -s P -d 'This option signals the application to activate visual feedback while reading…'
complete -c page -s T -d 'This option signals the application to collect statistics while reading the i…'
complete -c page -s D -d 'This option signals the application to activate logging in the Safe base, for…'
complete -c page -s r
complete -c page -o rd
complete -c page -l reader -d 'These options specify the plugin the application has to use for reading the i…'
complete -c page -s w
complete -c page -l writer -d 'These options specify the plugin the application has to use for generating an…'
complete -c page -s t
complete -c page -l transform -d 'These options specify a plugin to run on the input'
complete -c page -s p -s a -d transformations
complete -c page -l append -d 'These options signal the application that all following transformations shoul…'
complete -c page -l prepend -d 'These options signal the application that all following transformations shoul…'
complete -c page -l reset -d 'This option signals the application to clear the list of transformations'
complete -c page -l configuration -d 'This option causes the application to load a configuration file and/or plugin'

