# qpwgraph
# Autogenerated from man page /usr/share/man/man1/qpwgraph.1.gz
complete -c qpwgraph -s a -l activated -d 'Activated patchbay'
complete -c qpwgraph -s x -l exclusive -d 'Exclusive patchbay'
complete -c qpwgraph -s m -l minimized -d 'Start minimized'
complete -c qpwgraph -s h -l help -d 'Show help about command line options'
complete -c qpwgraph -s v -l version -d 'Show version information FILES Configuration settings are stored in ~/'

