# tcldocstrip
# Autogenerated from man page /usr/share/man/man1/tcldocstrip.1.gz
complete -c tcldocstrip -o guards -d 'This is the form for use case [3]'
complete -c tcldocstrip -o metaprefix -d 'This option is inherited from the command docstrip::extract provided by the p…'
complete -c tcldocstrip -o onerror -d 'This option is inherited from the command docstrip::extract provided by the p…'
complete -c tcldocstrip -o trimlines -d 'This option is inherited from the command docstrip::extract provided by the p…'
complete -c tcldocstrip -o preamble
complete -c tcldocstrip -o postamble
complete -c tcldocstrip -o nopreamble
complete -c tcldocstrip -o nopostamble -d 'The -no*amble options deactivate file pre- and postambles altogether, whereas…'

